bypass-alias-check-accounts:
  - "098217739820"

regions:
  - global
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - eu-west-1
  - eu-central-1
  - ap-southeast-1
  - ap-northeast-1

account-blocklist:
  - "000000000000" 

accounts:
  "098217739820": 
    filters:
      IAMUser:
        - type: "glob"
          value: "*" 
      S3Object:
        - type: "glob"
          value: "*"
      DynamoDBTableItem:
        - type: "glob"
          value: "*"
